/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VentasRouteImport } from './routes/ventas'
import { Route as StockRouteImport } from './routes/stock'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as ProveedoresRouteImport } from './routes/proveedores'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as NuevaVentaRouteImport } from './routes/nueva-venta'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as CombosRouteImport } from './routes/combos'
import { Route as IndexRouteImport } from './routes/index'

const VentasRoute = VentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProveedoresRoute = ProveedoresRouteImport.update({
  id: '/proveedores',
  path: '/proveedores',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevaVentaRoute = NuevaVentaRouteImport.update({
  id: '/nueva-venta',
  path: '/nueva-venta',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const CombosRoute = CombosRouteImport.update({
  id: '/combos',
  path: '/combos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/combos': typeof CombosRoute
  '/compras': typeof ComprasRoute
  '/configuracion': typeof ConfiguracionRoute
  '/historial': typeof HistorialRoute
  '/nueva-venta': typeof NuevaVentaRoute
  '/productos': typeof ProductosRoute
  '/proveedores': typeof ProveedoresRoute
  '/reportes': typeof ReportesRoute
  '/stock': typeof StockRoute
  '/ventas': typeof VentasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/combos': typeof CombosRoute
  '/compras': typeof ComprasRoute
  '/configuracion': typeof ConfiguracionRoute
  '/historial': typeof HistorialRoute
  '/nueva-venta': typeof NuevaVentaRoute
  '/productos': typeof ProductosRoute
  '/proveedores': typeof ProveedoresRoute
  '/reportes': typeof ReportesRoute
  '/stock': typeof StockRoute
  '/ventas': typeof VentasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/combos': typeof CombosRoute
  '/compras': typeof ComprasRoute
  '/configuracion': typeof ConfiguracionRoute
  '/historial': typeof HistorialRoute
  '/nueva-venta': typeof NuevaVentaRoute
  '/productos': typeof ProductosRoute
  '/proveedores': typeof ProveedoresRoute
  '/reportes': typeof ReportesRoute
  '/stock': typeof StockRoute
  '/ventas': typeof VentasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/combos'
    | '/compras'
    | '/configuracion'
    | '/historial'
    | '/nueva-venta'
    | '/productos'
    | '/proveedores'
    | '/reportes'
    | '/stock'
    | '/ventas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/combos'
    | '/compras'
    | '/configuracion'
    | '/historial'
    | '/nueva-venta'
    | '/productos'
    | '/proveedores'
    | '/reportes'
    | '/stock'
    | '/ventas'
  id:
    | '__root__'
    | '/'
    | '/combos'
    | '/compras'
    | '/configuracion'
    | '/historial'
    | '/nueva-venta'
    | '/productos'
    | '/proveedores'
    | '/reportes'
    | '/stock'
    | '/ventas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CombosRoute: typeof CombosRoute
  ComprasRoute: typeof ComprasRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  HistorialRoute: typeof HistorialRoute
  NuevaVentaRoute: typeof NuevaVentaRoute
  ProductosRoute: typeof ProductosRoute
  ProveedoresRoute: typeof ProveedoresRoute
  ReportesRoute: typeof ReportesRoute
  StockRoute: typeof StockRoute
  VentasRoute: typeof VentasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ventas': {
      id: '/ventas'
      path: '/ventas'
      fullPath: '/ventas'
      preLoaderRoute: typeof VentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proveedores': {
      id: '/proveedores'
      path: '/proveedores'
      fullPath: '/proveedores'
      preLoaderRoute: typeof ProveedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nueva-venta': {
      id: '/nueva-venta'
      path: '/nueva-venta'
      fullPath: '/nueva-venta'
      preLoaderRoute: typeof NuevaVentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combos': {
      id: '/combos'
      path: '/combos'
      fullPath: '/combos'
      preLoaderRoute: typeof CombosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CombosRoute: CombosRoute,
  ComprasRoute: ComprasRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  HistorialRoute: HistorialRoute,
  NuevaVentaRoute: NuevaVentaRoute,
  ProductosRoute: ProductosRoute,
  ProveedoresRoute: ProveedoresRoute,
  ReportesRoute: ReportesRoute,
  StockRoute: StockRoute,
  VentasRoute: VentasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
